---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: almalinux:8.5
    privileged: true
    command: /sbin/init
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
