---
# vars file for install_yum_items
yum_items_vars:
  - { name: 'nginx', state: 'present', exclude: '', enablerepo: '',  disablerepo: '', disable_gpg_check: 'false' }
  - { name: 'https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm', state: 'present', exclude: '', enablerepo: '',  disablerepo: '', disable_gpg_check: 'true' }
  - { name: 'zabbix-agent2', state: 'present', exclude: '', enablerepo: '',  disablerepo: '', disable_gpg_check: 'true' }
service_items_vars:
  - { name: 'nginx', state: 'started', enabled: 'true' }
  - { name: 'zabbix-agent2', state: 'started', enabled: 'true' }
