---
# tasks file for add_yum_repository
- name: Add yum repository.
  yum_repository:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    file: '{{ item.file }}'
    baseurl: '{{ item.baseurl }}'
    enabled: '{{ item.enabled }}'
    gpgcheck: '{{ item.gpgcheck }}'
  with_items:
    - '{{ yum_repository_vars }}'